### ISSUE TITLE
Remove action bug in MuRDAMap

### ISSUE THREAD

**Issue by LittleMorakot** [mikolalysenko/mudb#167]
After dispatch a remove action in MuRDAMap, if using `replica.state(stateA)` in change listener, the state in replica is not correctly copied into `stateA`

```
this.replica.configure({
    change: (newState) => {
        this.replica.state(this.state);
        // this.state is old state, but newState is correct
    },
});
```

**Comment by mikolalysenko** [comment]
Probably the issue is murdamap's store is broken.  It should be removing states from the old state, but it's not.
