### ISSUE TITLE
Better primitive type checking

### ISSUE THREAD

**Issue by hediyi** [mikolalysenko/mudb#230]
Maybe better to check `typeof identity` instead of `muType`, coz we don't have control over the type name of user-defined schema types

**Comment by hediyi** [comment]
take the example of the `QuantizedScalar`

**Comment by mikolalysenko** [comment]
No, the typeof identity is ambiguous.  We should use mutype for this stuff.

**Comment by hediyi** [comment]
i'm thinking something like `type === 'number' || type === 'string' || type === 'boolean'`, how is this ambiguous?

**Comment by mikolalysenko** [comment]
In what context would the typeof syntax get checked?

If you are serializing an 8 bit vs 32 bit vs var int you'd use a different technique.

**Comment by hediyi** [comment]
I see your point now. The semantics of the function is gonna be straightforward: is the corresponding data type of this schema a primitive in JS. By the result, we could decide whether or not to use the more optimized implementations for clone(), assign(), etc, just like what we're doing right now. 

So the benefit of this change is something like `new MuArray(new QuantizedScalar())` could have more efficient clone() and assign().
