### ISSUE TITLE
Should MuBuffer constructor also take Uint8Array as argument?

### ISSUE THREAD

**Issue by hediyi** [mikolalysenko/mudb#233]
could reduce some allocations in some situation like in the MuReadStream constructor

```ts
constructor (data:Uint8Array) {
    this.buffer = new MuBuffer(data.buffer);
}
```

**Comment by mikolalysenko** [comment]
No.  Because buffers are all pooled this could cause a memory leak.

**Comment by hediyi** [comment]
We don't pool readstream buffers. And `new MuBuffer()` always create a new Uint8Array any way. I'm thinking something like

```ts
constructor (buffer:ArrayBuffer|Uint8Array) {
  const uint8 = buffer instance of Uint8Array ? buffer : new Uint8Array(buf)
  this.buffer = uint8.buffer
  this.uint8 = uint8
  ...
}
```

Maybe i miss something here, how is this gonna cause a leak?

**Comment by mikolalysenko** [comment]
It may make stuff more complicated.  One thing to consider is that we may need to track byteOffset and byteLength from the uint8array.

**Comment by hediyi** [comment]
fair point! yea, it's gonna be complicated.. closing
