### ISSUE TITLE
MuRPC problems

### ISSUE THREAD

**Issue by mikolalysenko** [mikolalysenko/mudb#64]
* Server RPC handlers need a reference to the client initiating the RPC call
* RPC `error` replies should use a separate protocol to prevent namespace conflicts
* Server and client should be able to reuse names:
```javascript
{
	client: {
		sum: {
			0: new MuInt8(),
			1: new MuInt8(),
		}
	},
	server: {
		sum: {
			0: new MuInt32(),
			1: new MuInt32(),
		}
	}
}
```

**Comment by esdoppio** [comment]
do u think broadcasting RPCs to clients is useful?
